### ISSUE TITLE
Integração Angular Material

### ISSUE THREAD

**Issue by calebefazzani** [Equipe-HYVE/petshow-frontend#5]
Adicionar dependência [Angular Material](https://material.angular.io) ao projeto front para criação das interfaces

**Comment by nathaliafischer** [comment]
Tem um comando pronto que vai adicionar as dependências do Angular Material ao nosso projeto.
Preciso do Node instalado pra fazer isso.  Lembrar: npm install
Instalar o angular 
@angular/cli
https://material.angular.io/guide/getting-started

**Comment by nathaliafischer** [comment]
Relatório:
Instalar o node em nodejs.org 
Instalar o Git Bash
Instalar o VS Code
Se o VS Code der bug de "The window has crashed", tentar remover os arquivos temporários -> "%temp%" no cmd, deletar
Clonar o projeto pra uma pasta determinada
Abrir a pasta do projeto 
Escrever npm install no terminal
Após concluído, verificar instalalação pelo cmd, com o comando "npm -v"
Instalar o Angular CLI com o comando "npm install -g @angular/cli" no terminal
Adicionar o material do Angular com "ng add @angular/material" no terminal
Git: dei git init, apenas
Atualização às 23:17: mostra apenas a linha "Installing packages for tooling via npm", sem sair do lugar
